excluded:
 - FightPandemics/Configuration
 - Pods
file_length:
  warning: 1000
  error: 1500
line_length: 
  warning: 300 
  error: 350
  ignores_comments: true
  ignores_urls: true
identifier_name:
  excluded:
    - id
