os: osx
osx_image: xcode11.1
language: swift

install:
- pod install

script:
- xcodebuild build -scheme FightPandemics -workspace FightPandemics.xcworkspace/ -destination 'platform=iOS Simulator,OS=13.1,name=iPhone 11'

notifications:
  slack:
    rooms:
      - fightpandemics:AOdNIouF6Ye6DKo1RuaZK7pd
    if: branch = develop
    on_success: always
    on_failure: always
